"""
parameters.py — DEPRECATED: Thin re-exporter for the ``config`` package.

All parameters have been moved to the ``config/`` package for modularity.
This file re-exports everything from ``config`` for backward compatibility.

New code should import directly from ``config``:
    from config import NB_CLASSES, BATCH_SIZE, ...
    from config.validation import validate_full_config

Legacy imports (``import parameters as params``) continue to work.
"""

import warnings as _warnings

# Emit deprecation warning when someone imports parameters.py directly
_warnings.warn(
    "parameters.py is deprecated. Use `from config import ...` instead. "
    "See config/__init__.py for the new API.",
    PendingDeprecationWarning,
    stacklevel=2,
)

# Re-export everything from the config package
from config import *  # noqa: F401, F403, E402
from config import (  # noqa: F401, F403, E402
    NB_CLASSES,
    INPUT_CHANNELS,
    INPUT_WIDTH,
    INPUT_HEIGHT,
    INPUT_SHAPE,
    USE_GRAYSCALE,
    OUTPUT_DIR,
    DATA_SOURCES,
    AVAILABLE_MODELS,
    MODEL_ARCHITECTURE,
    USE_LOGITS,
    # Model-specific
    DEPTHWISE_FILTERS,
    POINTWISE_FILTERS,
    SIMPLE_CNN_FILTERS,
    SIMPLE_CNN_DENSE_UNITS,
    DIG_CLASS100_FILTERS,
    DIG_CLASS100_DENSE_UNITS,
    DROPOUT_RATE,
    ORIGINAL_HAVERLAND_FILTERS,
    ORIGINAL_HAVERLAND_DENSE_UNITS,
    ORIGINAL_HAVERLAND_DROPOUT_RATES,
    # Optimizer
    OPTIMIZER_TYPE,
    RMSPROP_RHO,
    RMSPROP_MOMENTUM,
    RMSPROP_EPSILON,
    ADAM_BETA_1,
    ADAM_BETA_2,
    ADAM_EPSILON,
    ADAM_AMSGRAD,
    SGD_MOMENTUM,
    SGD_NESTEROV,
    ADAGRAD_INITIAL_ACCUMULATOR,
    ADAGRAD_EPSILON,
    ADAMW_WEIGHT_DECAY,
    ADAMW_BETA_1,
    ADAMW_BETA_2,
    ADAMW_EPSILON,
    # Training
    SHUFFLE_SEED,
    VERBOSE,
    SAVE_TRAINING_PLOTS,
    LOSS_TYPE,
    LABEL_SMOOTHING,
    FOCAL_GAMMA,
    FOCAL_ALPHA,
    FOCAL_ACCURACY_THRESHOLDS,
    FOCAL_GAMMA_VALUES,
    FOCAL_GAMMA_RAMP_EPOCHS,
    FOCAL_PLATEAU_PATIENCE,
    FOCAL_PLATEAU_MIN_DELTA,
    USE_DYNAMIC_WEIGHTS,
    DYNAMIC_WEIGHTS_EPOCHS,
    BATCH_SIZE,
    EPOCHS,
    LEARNING_RATE,
    TRAINING_PERCENTAGE,
    VALIDATION_SPLIT,
    USE_LEARNING_RATE_SCHEDULER,
    LR_SCHEDULER_TYPE,
    LR_SCHEDULER_PATIENCE,
    LR_SCHEDULER_MIN_LR,
    LR_SCHEDULER_FACTOR,
    LR_SCHEDULER_MONITOR,
    USE_LR_WARMUP,
    LR_WARMUP_INITIAL_SCALE,
    EXPONENTIAL_DECAY_STEPS,
    EXPONENTIAL_DECAY_RATE,
    COSINE_DECAY_ALPHA,
    LR_WARMUP_EPOCHS,
    STEP_DECAY_STEP_SIZE,
    STEP_DECAY_GAMMA,
    USE_DYNAMIC_SCHEDULER,
    LR_SCHEDULER_THRESHOLDS,
    LR_SCHEDULER_SEQUENCE,
    LR_SCHEDULER_RESET_FRACTION,
    USE_DYNAMIC_OPTIMIZER,
    OPTIMIZER_SEQUENCE,
    # Regularization
    L1_REGULARIZATION,
    L2_REGULARIZATION,
    DEFAULT_DROPOUT_RATE,
    USE_BATCH_NORM,
    BATCH_NORM_MOMENTUM,
    BATCH_NORM_EPSILON,
    # Gradient
    USE_GRADIENT_CLIPPING,
    GRADIENT_CLIP_VALUE,
    GRADIENT_CLIP_NORM,
    WEIGHT_INITIALIZER,
    # Callbacks
    USE_EARLY_STOPPING,
    EARLY_STOPPING_PATIENCE,
    EARLY_STOPPING_MONITOR,
    EARLY_STOPPING_MIN_DELTA,
    RESTORE_BEST_WEIGHTS,
    SAVE_CHECKPOINTS,
    CHECKPOINT_FREQUENCY,
    SAVE_BEST_ONLY,
    CHECKPOINT_MONITOR,
    USE_TENSORBOARD,
    TENSORBOARD_UPDATE_FREQ,
    TENSORBOARD_WRITE_GRAPHS,
    RESUME_MODEL_PATH,
    INITIAL_EPOCH,
    # Quantization
    QUANTIZATION_MODE,
    QUANTIZE_MODEL,
    ESP_DL_QUANTIZE,
    USE_QAT,
    QAT_QUANTIZE_ALL,
    QAT_SCHEME,
    USE_TQT_PIPELINE,
    DISABLE_XNNPACK,
    USE_TFLITE_BUILTINS_INT8_ONLY,
    _TQT_DEFAULTS,
    TQT_NUM_BITS,
    TQT_TARGET,
    TQT_EXPORT_ALL_TARGETS,
    TQT_ALL_TARGETS,
    TQT_DEVICE,
    TQT_STEPS,
    TQT_LR,
    TQT_BLOCK_SIZE,
    TQT_INT_LAMBDA,
    TQT_IS_SCALE_TRAINABLE,
    TQT_IS_WEIGHT_TRAINABLE,
    TQT_COLLECTING_DEVICE,
    TQT_CALIB_STEPS,
    TQT_CALIB_BATCH_SIZE,
    USE_TQT_FOR_TFLITE,
    DATASET_CACHE_DIR,
    USE_TF_DATA_PIPELINE,
    TF_DATA_PARALLEL_CALLS,
    TF_DATA_PREFETCH_SIZE,
    TF_DATA_SHUFFLE_BUFFER,
    QUANTIZE_NUM_SAMPLES,
    # Tuner
    TUNER_MAX_TRIALS,
    TUNER_EPOCHS,
    TUNER_EARLY_STOPPING_PATIENCE,
    TUNER_OPTIMIZERS,
    TUNER_LEARNING_RATES,
    TUNER_BATCH_SIZES,
    TUNER_GAMMAS,
    TUNER_ALPHAS,
    TUNER_FINETUNE_EPOCHS,
    TUNER_FINETUNE_LRS,
    TUNER_FINETUNE_OPTIMIZERS,
    TUNER_LR_FACTORS,
    FINETUNE_UNFREEZE_LAST_N,
    USE_KERAS_TUNER,
    KERAS_TUNER_PROJECT_NAME,
    KERAS_TUNER_MAX_TRIALS,
    KERAS_TUNER_EXECUTIONS_PER_TRIAL,
    KERAS_TUNER_OBJECTIVE,
    KERAS_TUNER_NUM_TRIAL,
    KERAS_TUNER_EPOCHS,
    KERAS_TUNER_OPTIMIZERS,
    KERAS_TUNER_LEARNING_RATES,
    KERAS_TUNER_BATCH_SIZES,
    KERAS_TUNER_EARLY_STOPPING_PATIENCE,
    KERAS_TUNER_MIN_DELTA,
    # Data augmentation
    USE_DATA_AUGMENTATION,
    AUGMENTATION_ZOOM_RANGE,
    AUGMENTATION_ROTATION_RANGE,
    AUGMENTATION_CONTRAST_RANGE,
    AUGMENTATION_BRIGHTNESS_RANGE,
    AUGMENTATION_WIDTH_SHIFT_RANGE,
    AUGMENTATION_HEIGHT_SHIFT_RANGE,
    AUGMENTATION_HORIZONTAL_FLIP,
    AUGMENTATION_VERTICAL_FLIP,
    AUGMENTATION_POLARITY_INVERSION,
    USE_MIXUP,
    USE_CUTMIX,
    USE_RANDOM_ERASING,
    # GPU
    USE_GPU,
    GPU_MEMORY_GROWTH,
    GPU_MEMORY_LIMIT,
    # Advanced
    USE_MIXED_PRECISION,
    USE_GRADIENT_ACCUMULATION,
    ACCUMULATION_STEPS,
    USE_LEARNING_RATE_FINDER,
    USE_STOCHASTIC_WEIGHT_AVERAGING,
    USE_CYCLICAL_LEARNING_RATE,
    USE_MODEL_ENSEMBLE,
    ENSEMBLE_MODEL_COUNT,
    # Distillation
    DISTILLATION_TEMPERATURE,
    DISTILLATION_ALPHA,
    DISTILLATION_BETA,
    DISTILLATION_LOSS_WEIGHT,
    DISTILLATION_STRATEGY,
    DISTILLATION_EPOCHS,
    DISTILLATION_LEARNING_RATE,
    DISTILLATION_BATCH_SIZE,
    DISTILLATION_VALIDATION_SPLIT,
    DISTILLATION_EARLY_STOPPING_PATIENCE,
    DISTILLATION_MIN_DELTA,
    DISTILLATION_USE_MIXED_PRECISION,
    DISTILLATION_USE_GRADIENT_CLIPPING,
    DISTILLATION_GRADIENT_CLIP_VALUE,
    DISTILLATION_GRADIENT_CLIP_NORM,
    DISTILLATION_USE_LABEL_SMOOTHING,
    DISTILLATION_LABEL_SMOOTHING,
    DISTILLATION_USE_WEIGHT_DECAY,
    DISTILLATION_WEIGHT_DECAY,
    DISTILLATION_USE_DROPOUT,
    DISTILLATION_DROPOUT_RATE,
    DISTILLATION_USE_BATCH_NORM,
    DISTILLATION_BATCH_NORM_MOMENTUM,
    DISTILLATION_BATCH_NORM_EPSILON,
    DISTILLATION_USE_LEARNING_RATE_SCHEDULER,
    DISTILLATION_LR_SCHEDULER_TYPE,
    DISTILLATION_LR_SCHEDULER_PATIENCE,
    DISTILLATION_LR_SCHEDULER_MIN_LR,
    DISTILLATION_LR_SCHEDULER_FACTOR,
    DISTILLATION_LR_SCHEDULER_MONITOR,
    DISTILLATION_USE_EARLY_STOPPING,
    DISTILLATION_EARLY_STOPPING_PATIENCE,
    DISTILLATION_EARLY_STOPPING_MIN_DELTA,
    DISTILLATION_RESTORE_BEST_WEIGHTS,
    DISTILLATION_SAVE_CHECKPOINTS,
    DISTILLATION_CHECKPOINT_FREQUENCY,
    DISTILLATION_SAVE_BEST_ONLY,
    DISTILLATION_CHECKPOINT_MONITOR,
    DISTILLATION_USE_TENSORBOARD,
    DISTILLATION_TENSORBOARD_UPDATE_FREQ,
    DISTILLATION_TENSORBOARD_WRITE_GRAPHS,
    DISTILLATION_USE_MODEL_ENSEMBLE,
    DISTILLATION_ENSEMBLE_MODEL_COUNT,
    DISTILLATION_USE_MIXUP,
    DISTILLATION_USE_CUTMIX,
    DISTILLATION_USE_RANDOM_ERASING,
    DISTILLATION_USE_DATA_AUGMENTATION,
    DISTILLATION_AUGMENTATION_ZOOM_RANGE,
    DISTILLATION_AUGMENTATION_ROTATION_RANGE,
    DISTILLATION_AUGMENTATION_CONTRAST_RANGE,
    DISTILLATION_AUGMENTATION_BRIGHTNESS_RANGE,
    DISTILLATION_AUGMENTATION_WIDTH_SHIFT_RANGE,
    DISTILLATION_AUGMENTATION_HEIGHT_SHIFT_RANGE,
    DISTILLATION_AUGMENTATION_HORIZONTAL_FLIP,
    DISTILLATION_AUGMENTATION_VERTICAL_FLIP,
    DISTILLATION_AUGMENTATION_POLARITY_INVERSION,
    DISTILLATION_USE_GRADIENT_ACCUMULATION,
    DISTILLATION_ACCUMULATION_STEPS,
    DISTILLATION_USE_STOCHASTIC_WEIGHT_AVERAGING,
    DISTILLATION_USE_CYCLICAL_LEARNING_RATE,
    DISTILLATION_USE_LEARNING_RATE_FINDER,
    DISTILLATION_USE_MODEL_ENSEMBLE,
    DISTILLATION_ENSEMBLE_MODEL_COUNT,
    DISTILLATION_USE_MIXED_PRECISION,
    DISTILLATION_USE_GRADIENT_CLIPPING,
    DISTILLATION_GRADIENT_CLIP_VALUE,
    DISTILLATION_GRADIENT_CLIP_NORM,
    DISTILLATION_USE_LABEL_SMOOTHING,
    DISTILLATION_LABEL_SMOOTHING,
    DISTILLATION_USE_WEIGHT_DECAY,
    DISTILLATION_WEIGHT_DECAY,
    DISTILLATION_USE_DROPOUT,
    DISTILLATION_DROPOUT_RATE,
    DISTILLATION_USE_BATCH_NORM,
    DISTILLATION_BATCH_NORM_MOMENTUM,
    DISTILLATION_BATCH_NORM_EPSILON,
    DISTILLATION_USE_LEARNING_RATE_SCHEDULER,
    DISTILLATION_LR_SCHEDULER_TYPE,
    DISTILLATION_LR_SCHEDULER_PATIENCE,
    DISTILLATION_LR_SCHEDULER_MIN_LR,
    DISTILLATION_LR_SCHEDULER_FACTOR,
    DISTILLATION_LR_SCHEDULER_MONITOR,
    DISTILLATION_USE_EARLY_STOPPING,
    DISTILLATION_EARLY_STOPPING_PATIENCE,
    DISTILLATION_EARLY_STOPPING_MIN_DELTA,
    DISTILLATION_RESTORE_BEST_WEIGHTS,
    DISTILLATION_SAVE_CHECKPOINTS,
    DISTILLATION_CHECKPOINT_FREQUENCY,
    DISTILLATION_SAVE_BEST_ONLY,
    DISTILLATION_CHECKPOINT_MONITOR,
    DISTILLATION_USE_TENSORBOARD,
    DISTILLATION_TENSORBOARD_UPDATE_FREQ,
    DISTILLATION_TENSORBOARD_WRITE_GRAPHS,
    DISTILLATION_USE_MODEL_ENSEMBLE,
    DISTILLATION_ENSEMBLE_MODEL_COUNT,
    DISTILLATION_USE_MIXUP,
    DISTILLATION_USE_CUTMIX,
    DISTILLATION_USE_RANDOM_ERASING,
    DISTILLATION_USE_DATA_AUGMENTATION,
    DISTILLATION_AUGMENTATION_ZOOM_RANGE,
    DISTILLATION_AUGMENTATION_ROTATION_RANGE,
    DISTILLATION_AUGMENTATION_CONTRAST_RANGE,
    DISTILLATION_AUGMENTATION_BRIGHTNESS_RANGE,
    DISTILLATION_AUGMENTATION_WIDTH_SHIFT_RANGE,
    DISTILLATION_AUGMENTATION_HEIGHT_SHIFT_RANGE,
    DISTILLATION_AUGMENTATION_HORIZONTAL_FLIP,
    DISTILLATION_AUGMENTATION_VERTICAL_FLIP,
    DISTILLATION_AUGMENTATION_POLARITY_INVERSION,
    DISTILLATION_USE_GRADIENT_ACCUMULATION,
    DISTILLATION_ACCUMULATION_STEPS,
    DISTILLATION_USE_STOCHASTIC_WEIGHT_AVERAGING,
    DISTILLATION_USE_CYCLICAL_LEARNING_RATE,
    DISTILLATION_USE_LEARNING_RATE_FINDER,
    # Functions
    validate_hyperparameters,
    validate_quantization_parameters,
    get_model_filename,
    get_tflite_filename,
    get_float_tflite_filename,
    get_available_model_names,
)

# Backward-compatible aliases
update_derived_parameters = lambda: None  # no longer needed — config auto-computes
print_hyperparameters = lambda: None  # no longer needed — config auto-computes


# --------------------------------------------------------------------------- #
#  Backward-compatible utility functions
# --------------------------------------------------------------------------- #

def get_hyperparameter_summary():
    """Return a comprehensive summary of all hyperparameter settings."""
    from config import (
        NB_CLASSES, INPUT_SHAPE, MODEL_ARCHITECTURE, OPTIMIZER_TYPE,
        LEARNING_RATE, LOSS_TYPE, BATCH_SIZE, EPOCHS, LABEL_SMOOTHING,
        FOCAL_GAMMA, FOCAL_ALPHA, USE_DATA_AUGMENTATION, USE_QAT,
        QUANTIZE_MODEL, ESP_DL_QUANTIZE, USE_TQT_PIPELINE, QUANTIZATION_MODE,
        LR_SCHEDULER_TYPE, WEIGHT_INITIALIZER, USE_GPU, USE_MIXED_PRECISION,
        USE_GRADIENT_ACCUMULATION, USE_GRADIENT_CLIPPING, USE_EARLY_STOPPING,
        USE_LEARNING_RATE_SCHEDULER, USE_DYNAMIC_SCHEDULER, USE_DYNAMIC_OPTIMIZER,
        USE_DYNAMIC_WEIGHTS, USE_LR_WARMUP, USE_STOCHASTIC_WEIGHT_AVERAGING,
        USE_CYCLICAL_LEARNING_RATE, USE_LEARNING_RATE_FINDER, USE_MODEL_ENSEMBLE,
        USE_MIXUP, USE_CUTMIX, USE_RANDOM_ERASING, USE_TENSORBOARD,
        SAVE_CHECKPOINTS, RESTORE_BEST_WEIGHTS, USE_BATCH_NORM,
        L1_REGULARIZATION, L2_REGULARIZATION, DEFAULT_DROPOUT_RATE,
        TRAINING_PERCENTAGE, VALIDATION_SPLIT, OUTPUT_DIR, USE_GRAYSCALE,
        INPUT_CHANNELS, INPUT_WIDTH, INPUT_HEIGHT,
    )
    summary = {
        'model': {
            'architecture': MODEL_ARCHITECTURE,
            'input_shape': INPUT_SHAPE,
            'num_classes': NB_CLASSES,
        },
        'optimizer': {
            'type': OPTIMIZER_TYPE,
            'learning_rate': LEARNING_RATE,
        },
        'loss': {
            'type': LOSS_TYPE,
            'label_smoothing': LABEL_SMOOTHING,
            'focal_gamma': FOCAL_GAMMA,
            'focal_alpha': FOCAL_ALPHA,
        },
        'training': {
            'batch_size': BATCH_SIZE,
            'epochs': EPOCHS,
            'training_percentage': TRAINING_PERCENTAGE,
            'validation_split': VALIDATION_SPLIT,
            'use_lr_scheduler': USE_LEARNING_RATE_SCHEDULER,
            'lr_scheduler_type': LR_SCHEDULER_TYPE,
            'use_dynamic_scheduler': USE_DYNAMIC_SCHEDULER,
            'use_dynamic_optimizer': USE_DYNAMIC_OPTIMIZER,
            'use_dynamic_weights': USE_DYNAMIC_WEIGHTS,
            'use_lr_warmup': USE_LR_WARMUP,
            'weight_initializer': WEIGHT_INITIALIZER,
            'use_gradient_clipping': USE_GRADIENT_CLIPPING,
            'use_early_stopping': USE_EARLY_STOPPING,
            'use_tensorboard': USE_TENSORBOARD,
            'save_checkpoints': SAVE_CHECKPOINTS,
            'restore_best_weights': RESTORE_BEST_WEIGHTS,
        },
        'regularization': {
            'use_batch_norm': USE_BATCH_NORM,
            'l1_regularization': L1_REGULARIZATION,
            'l2_regularization': L2_REGULARIZATION,
            'dropout_rate': DEFAULT_DROPOUT_RATE,
        },
        'augmentation': {
            'use_data_augmentation': USE_DATA_AUGMENTATION,
            'use_mixup': USE_MIXUP,
            'use_cutmix': USE_CUTMIX,
            'use_random_erasing': USE_RANDOM_ERASING,
        },
        'quantization': {
            'quantization_mode': QUANTIZATION_MODE,
            'quantize_model': QUANTIZE_MODEL,
            'use_qat': USE_QAT,
            'use_tqt_pipeline': USE_TQT_PIPELINE,
            'esp_dl_quantize': ESP_DL_QUANTIZE,
        },
        'advanced': {
            'use_mixed_precision': USE_MIXED_PRECISION,
            'use_gradient_accumulation': USE_GRADIENT_ACCUMULATION,
            'use_stochastic_weight_averaging': USE_STOCHASTIC_WEIGHT_AVERAGING,
            'use_cyclical_lr': USE_CYCLICAL_LEARNING_RATE,
            'use_lr_finder': USE_LEARNING_RATE_FINDER,
            'use_model_ensemble': USE_MODEL_ENSEMBLE,
        },
        'hardware': {
            'use_gpu': USE_GPU,
            'output_dir': OUTPUT_DIR,
            'grayscale': USE_GRAYSCALE,
            'input_channels': INPUT_CHANNELS,
            'input_width': INPUT_WIDTH,
            'input_height': INPUT_HEIGHT,
        },
    }
    return summary


def print_hyperparameter_summary():
    """Print a formatted summary of all hyperparameter settings."""
    summary = get_hyperparameter_summary()
    print("\n" + "=" * 60)
    print("HYPERPARAMETER CONFIGURATION SUMMARY")
    print("=" * 60)
    for category, settings in summary.items():
        print(f"\n{category.upper()}:")
        for key, value in settings.items():
            if isinstance(value, dict):
                print(f"  {key}:")
                for k, v in value.items():
                    print(f"    {k}: {v}")
            else:
                print(f"  {key}: {value}")
    print("=" * 60 + "\n")


def get_hyperparameter_summary_text():
    """Return hyperparameter summary as formatted text for file export."""
    summary = get_hyperparameter_summary()
    lines = []
    lines.append("HYPERPARAMETER CONFIGURATION SUMMARY")
    lines.append("=" * 50)
    for category, settings in summary.items():
        lines.append(f"\n{category.upper()}:")
        for key, value in settings.items():
            if isinstance(value, dict):
                lines.append(f"  {key}:")
                for k, v in value.items():
                    lines.append(f"    {k}: {v}")
            else:
                lines.append(f"  {key}: {value}")
    return "\n".join(lines)
