FROM tensorflow/tensorflow:2.20.0-gpu

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY requirements.txt .

# Install packages
RUN pip3 install --no-cache-dir -r requirements.txt


COPY . .

#CMD ["python3", "-c", "import tensorflow as tf; import torch; print('Libraries imported successfully'); print('TF GPU:', len(tf.config.list_physical_devices('GPU')) > 0); print('PyTorch CUDA:', torch.cuda.is_available())"]
CMD ["bash"]
#CMD ["python3"]