"""
config/data_sources.py — Data source definitions.

DATA_SOURCES is dynamically built based on NB_CLASSES so that label files
and dataset paths use the correct class count.
"""

import sys

# Get NB_CLASSES from the parent config module (avoids circular import)
_config_mod = sys.modules.get('config')
if _config_mod is not None and hasattr(_config_mod, 'NB_CLASSES'):
    NB_CLASSES = _config_mod.NB_CLASSES
else:
    # Fallback: read from environment
    import os
    NB_CLASSES = int(os.environ.get("DIGIT_NB_CLASSES", "100"))
del _config_mod

DATA_SOURCES = [
    {
        'name': 'Tenth-of-step-of-a-meter-digit',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',
        'path': 'datasets/Tenth-of-step-of-a-meter-digit', 
        'weight': 3.0,  # ~22.6k images (Baseline)
    },
    {
        'name': 'real_integra_bad_predictions',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',  
        'path': 'datasets/real_integra_bad_predictions', 
        'weight': 10.0,  # ~1.8k images (Corrected bad predictions, highly weighted)
    },
    {
        'name': 'real_integra',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',  
        'path': 'datasets/real_integra', 
        'weight': 6.0,  # ~1.8k images (Small dataset, weighted for balance)
    },
    {
        'name': f'failed_predictions_{NB_CLASSES}',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',  
        'path': f'datasets/failed_predictions_{NB_CLASSES}', 
        'weight': 10.0,  # ~1k to 4.3k images (Corrected bad predictions, highly weighted)
    },
    {
        'name': 'static_augmentation',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',  
        'path': 'datasets/static_augmentation', 
        'weight': 1.0,  # ~70k images generated by static augmentation (Large dataset, slightly down-weighted)
        'is_synthetic': True,
    },
    {
        'name': 'static_augmentation_mixup',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',  
        'path': 'datasets/static_augmentation_mixup', 
        'weight': 1.0,  # ~3.3k images (Small dataset, weighted for for mixup bad classes)
        'is_synthetic': True,
    },
    {
        'name': f'GWF_watermeter',
        'type': 'label_file', 
        'labels': f'labels_{NB_CLASSES}_shuffle.txt',  
        'path': f'datasets/GWF_watermeter', 
        'weight': 6.0,  # ~0.8k images (Very small dataset, up-weighted)
    },
]
